server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: msv-citas
          uri: lb://msv-citas
          predicates:
            - Path=/api/citas/**

        - id: msv-medicos
          uri: lb://msv-medicos
          predicates:
            - Path=/api/medicos/**

        - id: msv-pacientes
          uri: lb://msv-pacientes
          predicates:
            - Path=/api/pacientes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true